CREATE SCHEMA cmpg323_accountsystem;

CREATE TABLE cmpg323_accountsystem.account_type (
  ACCOUNT_TYPE_ID int NOT NULL,
  MNEMONIC varchar(50) NOT NULL,
  ACCOUNT_TYPE_NAME varchar(50) NOT NULL,
  CREATION_DATE date NOT NULL,
  PRIMARY KEY (ACCOUNT_TYPE_ID)
);


CREATE TABLE cmpg323_accountsystem.demo_account_tx (
  ACCOUNT_TX_ID int NOT NULL,
  ACCOUNT_TYPE_ID int DEFAULT NULL,
  MEMBER_ID int DEFAULT NULL,
  AMOUNT int DEFAULT NULL,
  TX_DATE date DEFAULT NULL,
  PRIMARY KEY (ACCOUNT_TX_ID),
  CONSTRAINT ACCOUNT_TYPE_ID_FK FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES account_type (ACCOUNT_TYPE_ID)
);
